package org.example.fakeshop_clients.ui.theme

import androidx.compose.ui.graphics.Color
import org.example.fakeshop_clients.core.design.DesignTokens.Colors

// Light Theme Colors
val md_theme_light_primary = Color(Colors.Light.PRIMARY)
val md_theme_light_onPrimary = Color(Colors.Light.ON_PRIMARY)
val md_theme_light_primaryContainer = Color(Colors.Light.PRIMARY_CONTAINER)
val md_theme_light_onPrimaryContainer = Color(Colors.Light.ON_PRIMARY_CONTAINER)
val md_theme_light_secondary = Color(Colors.Light.SECONDARY)
val md_theme_light_onSecondary = Color(Colors.Light.ON_SECONDARY)
val md_theme_light_secondaryContainer = Color(Colors.Light.SECONDARY_CONTAINER)
val md_theme_light_onSecondaryContainer = Color(Colors.Light.ON_SECONDARY_CONTAINER)
val md_theme_light_background = Color(Colors.Light.BACKGROUND)
val md_theme_light_onBackground = Color(Colors.Light.ON_BACKGROUND)
val md_theme_light_surface = Color(Colors.Light.SURFACE)
val md_theme_light_surfaceVariant = Color(Colors.Light.SURFACE_VARIANT)
val md_theme_light_onSurface = Color(Colors.Light.ON_SURFACE)
val md_theme_light_onSurfaceVariant = Color(Colors.Light.ON_SURFACE_VARIANT)
val md_theme_light_surfaceContainerLowest = Color(Colors.Light.SURFACE_CONTAINER_LOWEST)
val md_theme_light_surfaceContainerLow = Color(Colors.Light.SURFACE_CONTAINER_LOW)
val md_theme_light_surfaceContainer = Color(Colors.Light.SURFACE_CONTAINER)
val md_theme_light_surfaceContainerHigh = Color(Colors.Light.SURFACE_CONTAINER_HIGH)
val md_theme_light_surfaceContainerHighest = Color(Colors.Light.SURFACE_CONTAINER_HIGHEST)
val md_theme_light_outline = Color(Colors.Light.OUTLINE)
val md_theme_light_outlineVariant = Color(Colors.Light.OUTLINE_VARIANT)
val md_theme_light_error = Color(Colors.Light.ERROR)
val md_theme_light_onError = Color(Colors.Light.ON_ERROR)
val md_theme_light_errorContainer = Color(Colors.Light.ERROR_CONTAINER)
val md_theme_light_onErrorContainer = Color(Colors.Light.ON_ERROR_CONTAINER)

// Dark Theme Colors
val md_theme_dark_primary = Color(Colors.Dark.PRIMARY)
val md_theme_dark_onPrimary = Color(Colors.Dark.ON_PRIMARY)
val md_theme_dark_primaryContainer = Color(Colors.Dark.PRIMARY_CONTAINER)
val md_theme_dark_onPrimaryContainer = Color(Colors.Dark.ON_PRIMARY_CONTAINER)
val md_theme_dark_secondary = Color(Colors.Dark.SECONDARY)
val md_theme_dark_onSecondary = Color(Colors.Dark.ON_SECONDARY)
val md_theme_dark_secondaryContainer = Color(Colors.Dark.SECONDARY_CONTAINER)
val md_theme_dark_onSecondaryContainer = Color(Colors.Dark.ON_SECONDARY_CONTAINER)
val md_theme_dark_background = Color(Colors.Dark.BACKGROUND)
val md_theme_dark_onBackground = Color(Colors.Dark.ON_BACKGROUND)
val md_theme_dark_surface = Color(Colors.Dark.SURFACE)
val md_theme_dark_surfaceVariant = Color(Colors.Dark.SURFACE_VARIANT)
val md_theme_dark_onSurface = Color(Colors.Dark.ON_SURFACE)
val md_theme_dark_onSurfaceVariant = Color(Colors.Dark.ON_SURFACE_VARIANT)
val md_theme_dark_surfaceContainerLowest = Color(Colors.Dark.SURFACE_CONTAINER_LOWEST)
val md_theme_dark_surfaceContainerLow = Color(Colors.Dark.SURFACE_CONTAINER_LOW)
val md_theme_dark_surfaceContainer = Color(Colors.Dark.SURFACE_CONTAINER)
val md_theme_dark_surfaceContainerHigh = Color(Colors.Dark.SURFACE_CONTAINER_HIGH)
val md_theme_dark_surfaceContainerHighest = Color(Colors.Dark.SURFACE_CONTAINER_HIGHEST)
val md_theme_dark_outline = Color(Colors.Dark.OUTLINE)
val md_theme_dark_outlineVariant = Color(Colors.Dark.OUTLINE_VARIANT)
val md_theme_dark_error = Color(Colors.Dark.ERROR)
val md_theme_dark_onError = Color(Colors.Dark.ON_ERROR)
val md_theme_dark_errorContainer = Color(Colors.Dark.ERROR_CONTAINER)
val md_theme_dark_onErrorContainer = Color(Colors.Dark.ON_ERROR_CONTAINER)
